-- VAMOS CRIAR UM CODIGO PARA TRABALHAR A VONTADE COM TABELAS
-- COM O BANCO DE DADOS SEMPRE SENDO INICIALIZADO DO ZERO

USE MASTER;
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'dbAula20260418_01')
BEGIN
	ALTER DATABASE dbAula20260418_01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE dbAula20260418_01;
END
GO
PRINT('NESTE PONTO A GARANTIA DE O BANCO NÃO EXISTIR.')
PRINT('POSSSO COMEÇAR O CÓDIGO DO ZERO E FICAR ALTERNANDO.')

CREATE DATABASE dbAula20260418_01;
GO

USE dbAula20260418_01;

CREATE TABLE ALUNO  (ID INT IDENTITY(1,1) PRIMARY KEY, NOME VARCHAR(30),);

INSERT INTO ALUNO (NOME) VALUES('DAVID');
INSERT INTO ALUNO (NOME) VALUES('WESLEY');
INSERT INTO ALUNO (NOME) VALUES('SOFIA');
INSERT INTO ALUNO (NOME) VALUES('HENRIQUE');

SELECT * FROM ALUNO;

ALTER TABLE ALUNO ADD NOTA FLOAT; -- ALTERA A ESTRUTURRA DA TABELA  E ADICIONA NOVA COLUNA

UPDATE ALUNO SET NOTA = 8.0 WHERE NOME = 'DAVID';
UPDATE ALUNO SET NOTA = 10.0 WHERE NOME = 'SOFIA';
--UPDATE ALUNO SET NOTA = 8.5 WHERE NOME = 'HENRIQUE';
UPDATE ALUNO SET NOTA = 5.0 WHERE NOME = 'WESLEY';
UPDATE ALUNO SET NOTA = 5.0 WHERE NOME = 'DAVI';
SELECT * FROM ALUNO;

ALTER TABLE ALUNO DROP COLUMN NOTA;

SELECT * FROM ALUNO WHERE NOME LIKE 'DA%';
SELECT * FROM ALUNO WHERE NOTA = 10.0;
SELECT * FROM ALUNO WHERE NOTA < 8.0 OR NOTA >=  9.0; -- MESMO QUE ACIMA (DE MORGAN)
SELECT * FROM ALUNO WHERE NOTA BETWEEN 5.0 AND 8.0
SELECT NOME, NOTA, 10.0 -  NOTA AS 'COMPLEMENTO', 2 * NOTA AS 'DOBRO' FROM ALUNO;

GO
CREATE VIEW NOTAS_ALTAS --CRIA UMA VIEW DA TABELA EM UM LOTE SEPARADO
AS
SELECT * FROM ALUNO WHERE NOTA >= 9.0;
GO

SELECT * FROM NOTAS_ALTAS;
SELECT * FROM ALUNO WHERE NOTA IS NULL;

GO
CREATE PROCEDURE CONSULTAR_ALUNO @NOME VARCHAR (30)
AS
BEGIN
	SELECT * FROM ALUNO WHERE NOME = @NOME;
END
GO
EXEC CONSULTAR_ALUNO @NOME = 'DAVID';
GO
CREATE PROCEDURE EXIBIR_ALUNO @ID INT= NULL, @NOME VARCHAR (30) = NULL
AS
BEGIN
	IF @ID IS NOT NULL
		SELECT * FROM ALUNO WHERE ID = @ID
	ELSE IF @NOME IS NOT NULL
		SELECT * FROM ALUNO WHERE NOME = @NOME
	ELSE
		PRINT('VOCÊ DEVE FORNECER ID OU NOME.')
	END
GO
EXEC EXIBIR_ALUNO @ID = 2
EXEC EXIBIR_ALUNO @NOME = 'SOFIA'
GO
CREATE PROCEDURE EXIBIR_NOTA @ID INT
AS
BEGIN
	DECLARE @NOTA FLOAT;
	SET @NOTA = (SELECT 1 NOTA FROM ALUNO WHERE ID = @ID)
	DECLARE @NOME VARCHAR (30)
	SET @NOME = (SELECT TOP 1 NOME FROM ALUNO WHERE ID = @ID)
	PRINT(@NOME + ' POSSUI NOTA = ' +  CAST(@NOTA AS CHAR(6) ) )
END
GO
EXEC EXIBIR_NOTA @ID = 2;
	
GO
ALTER DATABASE dbAula20260418_01 SET CONTAINMENT = PARTIAL;
GO


CREATE USER  USUARIO_01 WITH PASSWORD = 'SENHA123'; 

GRANT SELECT ON ALUNO TO USUARIO_01;-- AQUI CONCEDO A PERMISSÃO
--REVOKE SELECT ON ALUNO TO USUARIO_01; -- AQUI, REVOGA A PERMISSÃO

BEGIN TRY
	--LINHA ABAIXO COMM ERRO! USUARIO NÃO POSSUI PERMISSÃO
	EXECUTE AS USER = 'USUARIO_01' SELECT * FROM ALUNO;
	PRINT('USUARIO_01 EXECUTOU O COMANDO SELECT')
END TRY
BEGIN CATCH
	PRINT('USUARIO_01 NÃO TEM PERMISSÃO')
	REVERT
END CATCH
