USE MASTER;
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'dbEscola')
BEGIN
	ALTER DATABASE dbEscola SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE dbEscola;
END
GO

CREATE DATABASE dbEscola;
GO

USE dbEscola;

CREATE TABLE ALUNOS (ID INT IDENTITY (1,1) PRIMARY KEY, NOME VARCHAR(30));
CREATE TABLE DISCIPLINA (ID INT IDENTITY (1,1) PRIMARY KEY, NOME VARCHAR(30));
CREATE TABLE ALUNO_DISCIPLINA (ID_ALUNO INT, ID_DISCIPLINA INT, PRIMARY KEY(ID_ALUNO, ID_DISCIPLINA),
								FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID),
								FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID));

INSERT  INTO ALUNOS (NOME) VALUES('DAVID');
INSERT  INTO ALUNOS (NOME) VALUES('SOFIA');
INSERT  INTO ALUNOS (NOME) VALUES('HENRIQUE');
INSERT  INTO ALUNOS (NOME) VALUES('CLEIDEMARA');

INSERT  INTO DISCIPLINA (NOME) VALUES('MATEMATICA');
INSERT  INTO DISCIPLINA (NOME) VALUES('HISTORIA');
INSERT  INTO DISCIPLINA (NOME) VALUES('GEOGRAFIA');
INSERT  INTO DISCIPLINA (NOME) VALUES('ARTES');

SELECT * FROM ALUNOS;
SELECT * FROM DISCIPLINA;

INSERT ALUNO_DISCIPLINA (ID_ALUNO, ID_DISCIPLINA) VALUES(1,1); -- DAVID, MATEMATICA

SELECT * FROM ALUNO_DISCIPLINA;

SELECT ID_ALUNO, ALUNOS.NOME, ID_DISCIPLINA, DISCIPLINA.NOME FROM ALUNO_DISCIPLINA
JOIN ALUNOS ON ID_ALUNO = ALUNOS.ID
JOIN DISCIPLINA ON ID_DISCIPLINA = DISCIPLINA.ID