

-- VAMOS CRIAR CÓDIGO PARA TRABALHAR À VONTADE COM MANIPULAÇÃO
-- DE TABELAS, COM O BANCO DE DADOS SEMPRE SENDO INICIALIZADO
-- DO ZERO.

USE MASTER;

IF EXISTS ( SELECT * FROM SYS.DATABASES WHERE NAME = 'dbAula20260418_01' )
BEGIN
	ALTER DATABASE dbAula20260418_01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE dbAula20260418_01;
END;
GO
PRINT( 'NESSE PONTO HÁ A GARANTIA DE O BANCO NÃO EXISTIR.' )
PRINT( 'POSSO COMEÇAR O CÓDIGO DO ZERO E FICAR ALTERANDO.' )

CREATE DATABASE dbAula20260418_01;
GO

USE dbAula20260418_01;
GO

CREATE TABLE ALUNO ( ID INT IDENTITY ( 10, 2 ) PRIMARY KEY,
					 NOME VARCHAR ( 30 )
					);
INSERT INTO ALUNO ( NOME ) VALUES ( 'DAVI' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'DAVID' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'JOÃO' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'WESLLEY' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'JULIO' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'FELIPE' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'GUILHERME' );

SELECT * FROM ALUNO;
ALTER TABLE ALUNO ADD NOTA FLOAT;	-- ALTERA A ESTRUTURA DA TABELA
									-- ADICIONA NOVA COLUNA.

GO
SELECT * FROM ALUNO;
UPDATE ALUNO SET NOTA= 7.0 WHERE NOME = 'DAVI';
--UPDATE ALUNO SET NOTA= 7.5 WHERE NOME = 'JOÃO';
UPDATE ALUNO SET NOTA= 8.0 WHERE NOME = 'WESLLEY';
UPDATE ALUNO SET NOTA= 9.0 WHERE NOME = 'JULIO';
UPDATE ALUNO SET NOTA= 7.0 WHERE NOME = 'FELIPE';
UPDATE ALUNO SET NOTA= 7.5 WHERE NOME = 'DAVID'
UPDATE ALUNO SET NOTA= 9.5 WHERE NOME = 'GUILHERME';
GO
SELECT * FROM ALUNO -- WHERE NOME LIKE 'DAV%';
					--WHERE NOT ( NOTA >= 8.0 AND NOTA < 9.0 );
					--WHERE NOTA < 8.0 OR NOTA >= 9.0;	-- MESMO QUE ACIMA ( DE MORGAN ).
					--WHERE NOTA BETWEEN 7.5 AND 8.0;
					WHERE NOTA <> 8.0;
SELECT NOME, NOTA, 10.0 - NOTA AS 'COMPLEMENTO', 2 * NOTA AS 'DOBRO' FROM ALUNO;

GO								-- CRIAR VIEW EM LOTE SEPARADO.
CREATE VIEW NOTAS_ALTAS					-- CRIA UMA VIEW 
AS
SELECT * FROM ALUNO WHERE NOTA >= 9.0;
GO
CREATE VIEW ALUNOS_FILEIRA
AS
SELECT * FROM ALUNO WHERE NOME IN ( 'JOÃO', 'FELIPE', 'WESLLEY', 'GUILHERME' )
GO

SELECT * FROM NOTAS_ALTAS;
SELECT * FROM ALUNOS_FILEIRA;

SELECT * FROM ALUNO WHERE NOTA IS NULL;

GO
CREATE PROCEDURE CONSULTAR_ALUNO @NOME VARCHAR ( 30 )
AS
BEGIN
	SELECT * FROM ALUNO WHERE NOME = @NOME;
END
GO
EXEC CONSULTAR_ALUNO @NOME = 'DAVI';
GO
CREATE PROCEDURE EXIBIR_ALUNO @ID INT= NULL, @NOME VARCHAR ( 30 )= NULL
AS
BEGIN
	IF @ID IS NOT NULL
		SELECT * FROM ALUNO WHERE ID = @ID
	ELSE IF @NOME IS NOT NULL
		SELECT * FROM ALUNO WHERE NOME = @NOME
	ELSE
		PRINT( 'VOCÊ DEVE FORNECER ID OU NOME.' )
END
GO
EXEC EXIBIR_ALUNO @ID= 16
EXEC EXIBIR_ALUNO @NOME= 'DAVID'
GO
CREATE PROCEDURE EXIBIR_NOTA @ID INT
AS
BEGIN
	DECLARE @NOTA FLOAT;
	SET @NOTA= (SELECT TOP 1 NOTA FROM ALUNO WHERE ID = @ID)
	DECLARE @NOME VARCHAR ( 30 )
	SET @NOME= (SELECT TOP 1 NOME FROM ALUNO WHERE ID = @ID)
	PRINT( @NOME + ' POSSUI NOTA = ' + CAST( @NOTA AS CHAR( 6 ) ) )
END
GO
EXEC EXIBIR_NOTA @ID= 18

GO
ALTER DATABASE dbAula20260418_01 SET CONTAINMENT = PARTIAL;
GO
CREATE USER USUARIO_01 WITH PASSWORD = 'SENHA123';

GRANT SELECT ON ALUNO TO USUARIO_01; -- CONCEDENDO PERMISSÃO.

BEGIN TRY
	-- LINHA ABAIXO COM ERRO! USUÁRIO NÃO POSSUI PERMISSÃO!
	EXECUTE AS USER = 'USUARIO_01'	SELECT * FROM ALUNO;
	PRINT( 'USUARIO_01 EXECUTOU O COMANDO SELECT' )
END TRY
BEGIN CATCH
	PRINT( 'USUARIO_01 NÃO TEM PERMISSÃO')
	REVERT
END CATCH

GO
/*
REVOKE SELECT ON ALUNO TO USUARIO_01;	-- REVOGA A PERMISSÃO.
GO
BEGIN TRY
	-- LINHA ABAIXO COM ERRO! USUÁRIO NÃO POSSUI PERMISSÃO!
	EXECUTE AS USER = 'USUARIO_01'	SELECT * FROM ALUNO;
	PRINT( 'USUARIO_01 EXECUTOU O COMANDO SELECT' )
END TRY
BEGIN CATCH
	PRINT( 'USUARIO_01 NÃO TEM PERMISSÃO')
	REVERT
END CATCH
*/


-- ALTER TABLE ALUNO DROP COLUMN NOME;
-- SELECT * FROM ALUNO;		-- AGORA NÃO EXISTE MAIS A COLUNA NOME.




