

PRINT( 'USUÁRIO ANTES DO LOOP: '+  USER_NAME() );

-- CASO O CONTEXTO ESTEJA EM ALGUM USUÁRIO, EXECUTA REVERT EM LOOP ATÉ 
-- RETROCEDER A SYSADMIN.
DECLARE @CONTADOR INT;
SET @CONTADOR= 10;
WHILE @CONTADOR > 0 AND IS_SRVROLEMEMBER( 'SYSADMIN' ) <> 1
BEGIN
	REVERT;
	SET @CONTADOR= @CONTADOR - 1;
END
GO

PRINT( 'USUÁRIO APÓS O LOOP: '+  USER_NAME() );


USE MASTER;				-- CONTEXTO EM MASTER.
GO

-- SE O BANCO DE DADOS EXISTIR, É ELIMINADO.
IF EXISTS ( SELECT * FROM SYS.DATABASES WHERE NAME = 'dbTestePermissao' )
BEGIN
	ALTER DATABASE dbTestePermissao SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE dbTestePermissao;
END
GO

-- GARANTE QUE O SERVIDOR ACEITA BANCOS DE DADOS CONTIDOS.
-- EXEC SP_CONFIGURE 'CONTAINED DATABASE AUTHENTICATION', 1;
-- RECONFIGURE;
-- GO

-- CRIA O BANCO DE DADOS. 
CREATE DATABASE dbTestePermissao;
ALTER DATABASE dbTestePermissao SET CONTAINMENT = PARTIAL;
GO

USE dbTestePermissao;

CREATE TABLE DADOS_RESTRITOS ( ID INT IDENTITY( 1, 1 ) PRIMARY KEY,
									INFO VARCHAR ( 60 )
								 );

INSERT INTO DADOS_RESTRITOS ( INFO ) VALUES ( '* * * INFORMAÇÃO RESTRITA * * *' );

GO
CREATE PROCEDURE LER_DADOS_RESTRITOS
AS
BEGIN
	DECLARE @INFO VARCHAR ( 60 );
	SET @INFO= ( SELECT TOP 1 INFO FROM DADOS_RESTRITOS );
	PRINT( @INFO );
END;
GO

CREATE USER USUARIO_RESTRITO WITH PASSWORD = 'SENHA123';

PRINT( '---------------------------------------------' );
EXECUTE AS USER = 'USUARIO_RESTRITO';
PRINT( 'USUÁRIO TENTA ACESSO ANTES DA CONCESSÃO.' );

BEGIN TRY
	EXEC LER_DADOS_RESTRITOS;
	PRINT( 'USUÁRIO EXECUTOU A PROCEDURE ANTES DA CONCESSÃO.' );
END TRY
BEGIN CATCH
	PRINT( 'NÃO CONSEGUIU: PERMISSÃO AINDA NÃO CONCEDIDA.' )
END CATCH

REVERT;		-- REVERTE O CONTEXTO. RETORNANDO A SYSADMIN.

PRINT( '----------------------------------------------------' )
PRINT( 'AGORA A PERMISSÃO SERÁ CONCEDIDA AO USUÁRIO.' );

-- CONCEDE A PERMISSÃO À STORED PROCEDURE.
GRANT EXEC ON LER_DADOS_RESTRITOS TO USUARIO_RESTRITO;

EXECUTE AS USER = 'USUARIO_RESTRITO';
BEGIN TRY
	EXEC LER_DADOS_RESTRITOS;
	PRINT( 'USUÁRIO EXECUTOU APÓS RECEBER A CONCESSÃO.' );
END TRY
BEGIN CATCH
	PRINT( 'NÃO CONSEGUIU: MESMO COM A CONCESSÃO.' );
END CATCH;

REVERT;		-- REVERTE O USUÁRIO.

PRINT( '---------------------------------------------------' );
PRINT( 'AGORA A PERMISSÃO SERÁ REVOGADA DO USUÁRIO.' );

-- REVOGA A CONCESSÃO À STORED PROCEDURE.
REVOKE EXEC ON LER_DADOS_RESTRITOS TO USUARIO_RESTRITO;

EXECUTE AS USER = 'USUARIO_RESTRITO';
BEGIN TRY
	EXEC LER_DADOS_RESTRITOS;
	PRINT( 'USUÁRIO EXECUTOU ÁPÓS CONCESSÃO SER REVOGADA.' );
END TRY
BEGIN CATCH
	PRINT( 'NÃO CONSEGUIU: A CONCESSÃO FOI REVOGADA.' );
END CATCH

REVERT;		-- REVERTE O USUÁRIO.


