
-- CRIA UM BANCO DE DADOS SOMENTE SE NÃO EXISTIR PREVIAMENTE.
CREATE DATABASE IF NOT EXISTS BancoAluno;

USE BancoAluno;		-- DEFINE ESSE BANCO COMO CONTEXTO.

DROP TABLE IF EXISTS tbAluno; -- DESTRÓI A TABELA SE EXISTIR.
-- CRIA A TABELA.
-- O CAMPO ID É CHAVE PRIMÁRIA. NÃO PODE REPETIR NEM SER NULO.
CREATE TABLE tbAluno ( ID INT AUTO_INCREMENT, 
						NOME VARCHAR ( 30 ),
                        PRIMARY KEY ( ID ) );

DELETE FROM tbAluno;	-- DELETA TODAS AS LINHAS ANTES DE TUDO.

INSERT INTO tbAluno ( NOME ) VALUES ( 'FELIPE' );
INSERT INTO tbAluno ( NOME ) VALUES ( 'JOÃO' );
INSERT INTO tbAluno ( NOME ) VALUES ( 'DAVI' );
INSERT INTO tbAluno ( NOME ) VALUES ( 'DAVID' );
INSERT INTO tbAluno ( NOME ) VALUES ( 'FELIPE' );
INSERT INTO tbAluno ( NOME ) VALUES ( 'FABIANO' );
INSERT INTO tbAluno ( NOME ) VALUES ( 'KAUÊ' );
UPDATE tbAluno SET NOME= 'FABIANO 2' WHERE NOME = 'KAUÊ';

-- USANDO * POSSO EXIBIR TODAS AS COLUNAS DA CONSULTA.
SELECT * FROM tbAluno WHERE NOME LIKE 'F%';



-- DROP TABLE IF EXISTS tbAluno;		-- DESTRÓI A TABELA.

