
-- ISSO É UM COMENTÁRIO DE UMA ÚNICA LINHA.
/*
	ESSE É UM COMENTÁRIO
	DE MÚLTIPLAS LINHAS
*/
USE MASTER;		-- COLOCA O CONTEXTO EM MASTER.

IF EXISTS ( SELECT * FROM SYS.DATABASES WHERE NAME = 'dbAula20260418_01' )
BEGIN
	PRINT( ' O BANCO DE DADOS JÁ EXISTE. SERÁ DESTRUÍDO!' )
	-- CONFIGURA O BANCO PARA USUÁRIO ÚNICO E FINALIZA TRANSAÇÕES CORRENTES.
	ALTER DATABASE dbAula20260418_01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE dbAula20260418_01;	-- APAGA O BANCO DE DADOS.
END
ELSE
BEGIN
	PRINT( 'O BANCO NÃO EXISTE. SERÁ CRIADO AGORA.' )
	CREATE DATABASE dbAula20260418_01;	-- CRIA BANCO DE DADOS.
END

GO				-- CONFIRMA A EXECUÇÃO DO LOTE DE INSTRUÇÕES.

-- USE dbAula20260321_01;		-- COLOCA O CONTEXTO NO BANCO ATUAL.