
-- CÓDIGO MAIS COMPLEXO.
USE MASTER;		-- CONTEXTO EM MASTER.

-- VERIFICA SE O BANCO DE DE DADOS NÃO EXISTE.
IF NOT EXISTS ( SELECT * FROM SYS.DATABASES WHERE NAME = 'dbAula20260321_02' )
BEGIN
	PRINT( 'O BANCO DE DADOS NÃO EXISTE E SERÁ CRIADO.' );
	CREATE DATABASE dbAula20260321_02;
	PRINT( 'COMANDO DE CRIAÇÃO DO BANCO FOI EXECUTADO.' );
END
ELSE
	PRINT( 'O BANCO DE DE DADOS JÁ EXISTE!' );

GO -- GARANTE A FINALIZAÇÃO DO LOTE ACIMA.

USE dbAula20260321_02;		-- ALTERA O CONTEXTO PARA dbAula20260321_02 (NOSSO BANCO)

CREATE TABLE tbProfessor ( ID INT PRIMARY KEY,
							NOME VARCHAR ( 30 )
							);

INSERT INTO tbProfessor ( ID, NOME ) VALUES ( 1, 'GIOVANNI' );
INSERT INTO tbProfessor ( ID, NOME ) VALUES ( 2, 'PARDAL' );

SELECT * FROM tbProfessor;		-- CONSULTA A PROFESSORES CADASTRADOS.

IF OBJECT_ID( 'tbAluno', 'U' ) IS NULL
BEGIN
	PRINT( 'A TABELA tbAluno NÃO EXISTE. SERÁ CRIADA!' );
	CREATE TABLE tbAluno ( RA DECIMAL( 7 ) PRIMARY KEY, -- CHAVE PRIMÁRIA.
						   NOME VARCHAR ( 30 ),
						   ID_PROF INT,   -- CADA ALUNO REFERENCIA UM PROFESSOR.
						   -- CHAVE ESTRANGEIRA.
						   FOREIGN KEY (ID_PROF) REFERENCES tbProfessor (ID)
						   );
END
ELSE
	PRINT( 'A TABELA tbAluno JÁ EXISTE!' );

DELETE FROM tbALUNO;		-- DELETA TODAS AS LINHAS DA TABELA.

-- AGORA VAMOS INSERIR LINHAS NA TABELA.
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510021, 'JOÃO', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510022, 'DAVI', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510027, 'FELIPE', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510028, 'WESLLEY', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510025, 'ANA', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510026, 'GUILHERME', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2510029, 'DAVID', 1 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2511101, 'HUGUINHO', 2 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2511102, 'ZEZINHO', 2 );
INSERT INTO tbALUNO ( RA, NOME, ID_PROF ) VALUES ( 2511103, 'LUISINHO', 2 );



SELECT * FROM tbALUNO; --  WHERE NOME LIKE '_E%';

-- CONSULTA COM JOIN. CONSULTA DUAS TABELAS SIMULTANEAMENTE.
SELECT RA, tbAluno.NOME AS 'NOME ALUNO',
		ID_PROF, tbProfessor.NOME AS 'NOME PROF.'
FROM tbAluno
JOIN tbProfessor ON tbAluno.ID_PROF = tbProfessor.ID;

-- NO FINAL, DESTRÓI O BANCO DE DADOS.
USE MASTER;
ALTER DATABASE dbAula20260321_02 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE dbAula20260321_02;