
-- ISSO É UM COMENTÁRIO.
USE MASTER;		-- CONTEXTO EM MASTER.

CREATE DATABASE dbAula20260321_01;	-- CRIA BANCO DE DADOS.

--GO			-- FINAL DE UM LOTE DE INSTRUÇÕES.
USE dbAula20260321_01;	-- CONTEXTO NO BANCO CRIADO.

CREATE TABLE tbALUNO ( RA DECIMAL( 7 ),
						NOME VARCHAR ( 60 )
					 );
INSERT INTO tbALUNO ( RA, NOME ) VALUES ( 2510021, 'DAVID' );

SELECT * FROM tbALUNO WHERE NOME = 'ANA';


