
USE MASTER;

IF EXISTS ( SELECT * FROM SYS.DATABASES WHERE NAME = 'dbEscola' )
BEGIN
	PRINT( 'O BANCO SERÁ DESTRUÍDO.' )
	ALTER DATABASE dbEscola SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE dbEscola;
END
GO

CREATE DATABASE dbEscola
GO

USE dbEscola;

CREATE TABLE ALUNO ( ID INT IDENTITY ( 1, 1 ) PRIMARY KEY,
					 NOME VARCHAR ( 30 )
					 );

CREATE TABLE DISCIPLINA ( ID INT IDENTITY ( 100, 1 ) PRIMARY KEY,
					NOME VARCHAR ( 30 )
					);

CREATE TABLE ALUNO_DISCIPLINA ( ID_ALUNO INT,
								ID_DISCIPLINA INT,
								AVA DECIMAL ( 4, 2 ),
								PROVA DECIMAL ( 4, 2 ),
								PIM DECIMAL ( 4, 2 ),
								PRIMARY KEY ( ID_ALUNO, ID_DISCIPLINA ), --CHAVE PRIMÁRIA COMPOSTA
								FOREIGN KEY ( ID_ALUNO ) REFERENCES ALUNO ( ID ), --CHAVE ESTRANGEIRA
								FOREIGN KEY ( ID_DISCIPLINA ) REFERENCES DISCIPLINA ( ID )
							   );

INSERT INTO ALUNO ( NOME ) VALUES ( 'ASDRUBAL' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'BELTRANO' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'CICRANO' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'EUSTAQUIO' );
INSERT INTO ALUNO ( NOME ) VALUES ( 'FULANO' );

INSERT INTO DISCIPLINA ( NOME ) VALUES ( 'MATEMATICA' );
INSERT INTO DISCIPLINA ( NOME ) VALUES ( 'POO' );
INSERT INTO DISCIPLINA ( NOME ) VALUES ( 'BANCO DE DADOS' );

SELECT * FROM ALUNO;
SELECT * FROM DISCIPLINA;

INSERT INTO ALUNO_DISCIPLINA ( ID_ALUNO, ID_DISCIPLINA ) VALUES ( 1, 100 ); --ASDRUBAL, MATEMATICA
INSERT INTO ALUNO_DISCIPLINA ( ID_ALUNO, ID_DISCIPLINA ) VALUES ( 1, 101 ); --ASDRUBAL, POO
INSERT INTO ALUNO_DISCIPLINA ( ID_ALUNO, ID_DISCIPLINA ) VALUES ( 2, 100 ); --BELTRANO, MATEMATICA

-- ASDRUBAL TIROU 7.5 NA PROVA DE MATEMÁTICA.
UPDATE ALUNO_DISCIPLINA SET AVA= 8.0 WHERE ID_ALUNO = 1 AND ID_DISCIPLINA = 100;
UPDATE ALUNO_DISCIPLINA SET PROVA= 6.0 WHERE ID_ALUNO = 1 AND ID_DISCIPLINA = 100;

SELECT * FROM ALUNO_DISCIPLINA;

SELECT ID_ALUNO, 
		ALUNO.NOME AS 'NOME ALUNO',
		ID_DISCIPLINA, 
		DISCIPLINA.NOME AS 'NOME DISC.',
		COALESCE( CAST( AVA AS CHAR(6)), ' -- ') AS 'AVA',
		COALESCE( CAST( PROVA AS CHAR(6)), ' -- ') AS 'PROVA',
		COALESCE( CAST( PIM AS CHAR(6)), ' -- ') AS 'PIM'
FROM ALUNO_DISCIPLINA
JOIN ALUNO ON ID_ALUNO = ALUNO.ID
JOIN DISCIPLINA ON ID_DISCIPLINA = DISCIPLINA.ID;



