USE MASTER;

IF NOT EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'db_aula20260321_02')
BEGIN
	PRINT('BANCO DE DADOS NÃO EXISTE E SERÁ CRIADO.');
	CREATE DATABASE db_aula20260321_02;
	PRINT('BANCO DE DADOS FOI CRIADO.');
END
ELSE
	PRINT('BANCO DE DADOS JÁ EXISTE.');
GO

USE db_aula20260321_02;

CREATE TABLE tbProfessor(ID INT PRIMARY KEY, NOME VARCHAR(30))

INSERT INTO tbProfessor(ID, NOME) VALUES(1, 'Giovanni');
INSERT INTO tbProfessor(ID, NOME) VALUES(2, 'Pardal');

SELECT * FROM tbProfessor;

IF OBJECT_ID('tbAluno','U') IS NULL
BEGIN
	PRINT('A TABELA tbAluno NÃO EXISTE. SERÁ CRIADA!');
	CREATE TABLE tbAluno(
		RA DECIMAL(7) PRIMARY KEY, --CHAVE PRIMARIA
						NOME VARCHAR(60), -- NOME DO ALUNO
						ID_PROF INT, -- CADA ALUNO REFERENCIA UM PROFESSOR
						FOREIGN KEY(ID_PROF) REFERENCES tbProfessor (ID));--CHAVE ESTRANGEIRA
END
ELSE
	PRINT('A TABELA tbAluno JÁ EXISTE.');

INSERT INTO tbAluno (RA, NOME, ID_PROF) VALUES ( 2034960, 'David', 1);
INSERT INTO tbAluno (RA, NOME, ID_PROF) VALUES ( 2035960, 'Danilo', 1);
INSERT INTO tbAluno (RA, NOME, ID_PROF) VALUES ( 2036960, 'Davi', 1);
INSERT INTO tbAluno (RA, NOME, ID_PROF) VALUES ( 6436960, 'Sofia', 1);
INSERT INTO tbAluno (RA, NOME, ID_PROF) VALUES ( 2132966, 'Henrique', 1);

SELECT * FROM tbAluno WHERE NOME LIKE 'Da%';

SELECT  RA, tbAluno.NOME AS 'NOME ALUNO', 
	ID_PROF, tbProfessor.NOME AS 'NOME PROF.'
FROM tbAluno
JOIN tbProfessor ON tbAluno.ID_PROF = tbProfessor.ID;


USE MASTER;
ALTER DATABASE db_aula20260321_02 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE db_aula20260321_02;
